chore(build): conditionally enable pretty printing

diff --git a/scripts/test_multi b/scripts/test_multi
--- a/scripts/test_multi
+++ b/scripts/test_multi
@@ -11,16 +11,16 @@ life_dir=$prj_root
 life_exe=$rel_bin_dir/multithreaded_life
 life_dbg=$dbg_bin_dir/multithreaded_life
 
-# args=" -s 3 -c 5 -i 011110010"
 # blinker
-args=" -s 3 -c 10 -i 010010010 -g 3"
-# args="-s 20 -c 100 -i 011001010110101111011001010110101111010111101010101111100110111"
+# args=" -s 3 -c 10 -g 1 -i 000111"
+# glider & blinker
+args=" -s 10 -c 10 -g 4 -i 010000000000100011101110000000"
 
 # build
 echo "Building life binaries..."
 echo ""
 cd $life_dir
-make DBG=true multi || { x=$? printf "failed while building, bailing...\n\n\n"; exit $x; }
+make PRETTY=true DBG=true multi || { x=$? printf "failed while building, bailing...\n\n\n"; exit $x; }
 echo "Executing multi w/ args '$args'..."
 echo ""
 $life_dbg $args || { x=$? printf "failed while executing '$args', bailing...\n\n\n"; exit $x; }
