chore(dev): remove unneeded step from test script

diff --git a/scripts/test_life b/scripts/test_life
--- a/scripts/test_life
+++ b/scripts/test_life
@@ -18,7 +18,7 @@ args=" -s 3 -c 5 -i 011110010"
 echo "Building life binaries..."
 echo ""
 cd $life_dir
-make list && make -d DBG=true life || { x=$? printf "failed while building, bailing...\n\n\n"; exit $x; }
+make DBG=true life || { x=$? printf "failed while building, bailing...\n\n\n"; exit $x; }
 echo "Executing life w/ args '$args'..."
 echo ""
 $life_dbg $args || { x=$? printf "failed while executing '$args', bailing...\n\n\n"; exit $x; }
